Javascript capstone: Feature/hit api
Gnwin/TV-App pull request #27
Opened 2022-04-23 22:29 UTC by Gnwin

# Javascript Capstone Project

In this project, we used kanban board, webpack, apis to build a mini tv app.(Javascript capstone project)

according to this requirement:

https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md

2022-04-23 22:56 UTC, brytebee requested changes
Hi, Team👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴🔴

![](https://media.giphy.com/media/KCfpWuNnTcLbc3aLvZ/giphy.gif)

You have submitted a project, that has failed linters, Kindly fix them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-24 02:07 UTC, Meltrust requested changes
Hi @Gnwin,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Very nice implementation! Looking great!✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the requirements:\

![image](https://user-images.githubusercontent.com/57421823/164952537-93e461ac-1173-4328-aad9-256902aba4bb.png)

Therefore, please make a video that meets all the requirements listed above.  Kindly remember, that the next reviewer will check if the video exists, and meets all the requirements.

Please, provide a link to this video.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-24 02:07 UTC, Meltrust commented on src/assets/js/modules/__tests__/App.test.js
> +// test
According to the requirements:

![image](https://user-images.githubusercontent.com/57421823/164952455-57c3f1b6-9a7b-47d2-b059-bcc7c1d90c38.png)

Therefore:

- [x] Please, include unit tests for all the counters, as required.

That way, we will meet this requirement 💪

2022-04-24 02:07 UTC, Meltrust commented on src/assets/stylesheets/style.css
> +.html {
- [ ] OPTIONAL: I highly suggest you align these "comment" buttons.  Your app will look a lot better:

![image](https://user-images.githubusercontent.com/57421823/164952610-2bc6535f-64f9-4ada-bceb-a206aca50b49.png)

2022-04-24 02:07 UTC, Meltrust commented on src/assets/stylesheets/style.css
> +} */
- [ ] Please, delete this old piece of commented code, in order to improve the cleanliness of the repo 💪

2022-04-24 02:07 UTC, Meltrust commented on src/assets/stylesheets/style.css
> +.html {
- [ ]  OPTIONAL:  I can see you did a mobile view for your app! Congratulations.  I recommend fixing the header, so all the elements are accessible, or even hide the ones that are not used:

![image](https://user-images.githubusercontent.com/57421823/164952751-2ae1117c-e88b-40e1-8c2e-25bf869f9782.png)

![image](https://user-images.githubusercontent.com/57421823/164952757-090e90ac-81fd-4986-a0e3-0c3a80ca2cf7.png)

2022-04-24 05:38 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @Gnwin, @karam084 👋🏻, 

Good job making the requested changes 💪🏻! Your project looks amazing 🤩.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
![rosycheeks-mochi-peach](https://user-images.githubusercontent.com/4247740/164958253-2aad9738-84f2-40de-8886-260f7b7071d2.gif)

2022-04-24 05:47 UTC, merged